### PR TITLE
🐛 Bootloader: Bail early on `wp-login.php`/`wp-admin`, and some other `/wp-` requests

### LINKED ISSUE #337: Changes to WordPress routes break the wp-admin login
### Version

v4.0.0

### What did you expect to happen?

Login into backend works as usual

### What actually happens?

After submitting the login credentials, I'll be "redirected" to the login form. On first attempt WordPress hints that cookies might be forbidden / deactivated.

### Steps to reproduce

- Upgrade to v4.0.0
- Try to login from `wp-login.php`

### PR DESCRIPTION
**Pull request by retlehs**
* [x] Fix wp-login.php
* [x] Fix wp-admin / admin-ajax.php requests
* [x] Fix other requests? wp-comments-post.php, wp-signup.php?

Fix #337

### CODE REVIEW

File: src/Roots/Acorn/Bootloader.php [hunk 1]
```diff
@@ -261,6 +261,14 @@ protected function registerRequestHandler(
         ?\Illuminate\Routing\Route $route,
         array $config
     ) {
+        if (strpos($request->getRequestUri(), '/wp-login.php') !== false) {
+            add_filter('do_parse_request', function ($doParse, \WP $wp, $extraQueryVars) {
+                return false;
+            }, 100, 3);
```
Comment (QWp6t) [inline src/Roots/Acorn/Bootloader.php:267]:
```suggestion
            add_filter('do_parse_request', '__return_false', 100, 3);
```

**Comment by dsturm** [comment]
Thanks for starting a fix so quickly.

I also noticed that there were problems with REST queries in the block editor. But I'm not sure if it's just the cookie not being set.

**Comment by retlehs** [comment]
Pushed an update that should fix those I think? If not, do you mind showing which requests are failing for you still?

**Comment by dsturm** [comment]
@retlehs Worked for me! Thanks 💪

**Review by QWp6t — APPROVED** [review]
LGTM! :shipit:

**Comment by dr5hn** [comment]
@QWp6t //cc @retlehs Doesn't work if we've hided login behind some custom path.

**Comment by retlehs** [comment]
@dr5hn Does `get_admin_url()` return the correct URL on your setup?

**Comment by dr5hn** [comment]
@retlehs Yes it return the hidden admin path url.

https://x***x.com/secret/

When i make this change, login works!

```
diff --git a/src/Roots/Acorn/Bootloader.php b/src/Roots/Acorn/Bootloader.php
index fc0e8c9..b57adfc 100644
--- a/src/Roots/Acorn/Bootloader.php
+++ b/src/Roots/Acorn/Bootloader.php
@@ -266,6 +266,7 @@ class Bootloader
             '/wp-login.php',
             '/wp-signup.php',
             '/wp-admin/',
+            '/secret/'
         ])) {
             return; // Let WordPress handle these requests
         }
```
